# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with maven
      run: mvn clean package -DskipTests --file pom.xml
    - name: Test with maven
      run: mvn test
      
    - name: Log into
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
        registry: ${{ env.REGISTRY }}
        username: 'arturouce35'
        password: 'Hellsing.35'
          
      
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
      with:
          context: .
          push: 'true'
          tags: 'arturouce35/demo-spring-dev:demo-spring-dev-latest'
          labels: 'demo'
  
  deploy:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: DigitalOcean App Platform deployment
      uses: digitalocean/app_action@main
      with:
        app_name: ubuntu-s-1vcpu-1gb-amd-sfo3-01
        token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
        images: '[
                  {
                    "name": "demo-spring-dev",
                     "image": {
                      "registry_type": "DOCR",
                      "repository": "arturouce35/demo-spring-dev",
                      "tag": "demo-spring-dev-latest"
                    },
                  }
                ]'
    #- name: Deploy with maven 
    #  uses: appleboy/ssh-action@v0.1.2
    #  with: 
    #    host: ${{secrets.SSH_HOST_DEMO_SPRING_DEV}}  
    #    password: ${{secrets.SSH_KEY_DEMO_SPRING_DEV}} 
    #    username: ${{secrets.SSH_USER_DEMO_SPRING_DEV}}
      
