# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Deploy maven project
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        host: ${{secrets.SSH_HOST_DEMO_SPRING_DEV}}  
        key: ${{secrets.SSH_KEY_DEMO_SPRING_DEV}} 
        username: ${{secrets.SSH_USER_DEMO_SPRING_DEV}}
        
        script: | 
          mkdir demo
          cd demo
          git clone https://github.com/arturouce/demo-spring.git
          echo 'deployment successfully'
